CARD_SETS = [(10000, 'Basic'),
             (10001, 'Classic'),
             (10002, 'Darkness Evolved'),
             (10003, 'Rise of Bahamut'),
             (10004, 'Tempest of the Gods'),
             (10005, 'Wonderland Dreams'),
             (10006, 'Starforged Legends'),
             (10007, 'Chronogenesis'),
             (10008, 'Dawnbreak,Nightedge'),
             (10009, 'Brigade of the Sky'),
             (10010, 'Omen of the Ten'),
             (10011, 'Altersphere'),
             (10012, 'Steel Rebellion'),
             (10013, 'Rebirth of Glory'),
             (10014, 'Verdant Conflict'),
             (10015, 'Ultimate Colosseum'),
             (10016, 'World Uprooted'),
             (10017, 'Fortune\'s Hand'),
             (10018, 'Storm Over Rivayle'),
             (10019, 'Eternal Awakening'),
             (10020, 'Darkness Over Vellsar'),
             (10021, 'Renascent Chronicles'),
             (10022, 'Dawn of Calamity'),
             (10023, 'Omen of Storms'),
             (10024, 'Edge of Paradise'),
             (10025, 'Roar of the Godwyrm'),
             (10026, 'Celestial Dragonblade'),
             (70001, 'Prebuilt Decks Set 1'),
             (70002, 'Prebuilt Decks Set 2'),
             (70003, 'Anigera Didoooon Tie-in'),
             (70004, 'Fate/stay night [Heaven\'s feel] Tie-in'),
             (70005, 'Prebuilt Decks Set 4'),
             (70006, 'Prebuilt Decks Set 5'),
             (70008, 'Princess Connect! Re:Dive Tie-in'),
             (70009, 'One-Punch Man Tie-in'),
             (70010, 'Re:ZERO Tie-in'),
             (70011, 'Prebuilt Decks Set 6'),
             (70012, 'Love Live! School Idol Festival Tie-in'),
             (70013, 'The Melancholy of Haruhi Suzumiya Tie-in'),
             (70014, 'Prebuilt Decks Set 7'),
             (70015, 'The Idolmaster: Cinderella Girls Tie-in'),
             (70016, 'NieR:Automata Tie-in'),
             (70017, 'Code Geass Lelouch of the Rebellion Tie-in'),
             (70018, 'Shadowverse: Champion\'s Battle Tie-in'),
             (70019, 'Shadowverse: Champion\'s Battle Set'),
             (70020, 'Granblue Fantasy Tie-in'),
             (70021, 'Battle Pass'),
             (70022, 'Kaguya-sama: Love Is War? Tie-in'),
             (70023, 'The Idolmaster: Cinderella Girls Tie-in'),
             (70024, 'Shaman King Tie-in'),
             (70025, 'Umamusume: Pretty Derby Tie-in'),
             (70026, 'Chiikawa Tie-in'),
             (70027, 'Shadowverse Flame Tie-in'),
             (90000, 'Tokens')
            ]

CARD_RARITYS = [(1, 'Bronze'),
                (2, 'Silver'),
                (3, 'Gold'),
                (4, 'Legendary')
               ]

CARD_TYPES = [(1, 'Follower'),
              (2, 'Amulet'),
              (3, 'Countdown Amulet'),
              (4, 'Spell')
             ]

CRAFTS = [(0, 'Neutral'),
          (1, 'Forestcraft'),
          (2, 'Swordcraft'),
          (3, 'Runecraft'),
          (4, 'Dragoncraft'),
          (5, 'Shadowcraft'),
          (6, 'Bloodcraft'),
          (7, 'Havencraft'),
          (8, 'Portalcraft')
             ]
